// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3YbhVZWaKsMoSCPgGloiuRj-s6VSbzs4',
    appId: '1:295635931500:web:fb2c82c8c506bad1fb6349',
    messagingSenderId: '295635931500',
    projectId: 'eyyubiyepersonel',
    authDomain: 'eyyubiyepersonel.firebaseapp.com',
    storageBucket: 'eyyubiyepersonel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRYzhy5J3R6_gtnumESYb39645ekWmcaY',
    appId: '1:295635931500:android:aecdef6cd4d9fe4bfb6349',
    messagingSenderId: '295635931500',
    projectId: 'eyyubiyepersonel',
    storageBucket: 'eyyubiyepersonel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCITEW2dTYGh3r-C7ZwZH-r8SPBcNVT-CE',
    appId: '1:295635931500:ios:c6a0a448f4bd3fe2fb6349',
    messagingSenderId: '295635931500',
    projectId: 'eyyubiyepersonel',
    storageBucket: 'eyyubiyepersonel.firebasestorage.app',
    iosBundleId: 'com.example.eyyubiyePersonelTakip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCITEW2dTYGh3r-C7ZwZH-r8SPBcNVT-CE',
    appId: '1:295635931500:ios:c6a0a448f4bd3fe2fb6349',
    messagingSenderId: '295635931500',
    projectId: 'eyyubiyepersonel',
    storageBucket: 'eyyubiyepersonel.firebasestorage.app',
    iosBundleId: 'com.example.eyyubiyePersonelTakip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3YbhVZWaKsMoSCPgGloiuRj-s6VSbzs4',
    appId: '1:295635931500:web:982981b13bb33e27fb6349',
    messagingSenderId: '295635931500',
    projectId: 'eyyubiyepersonel',
    authDomain: 'eyyubiyepersonel.firebaseapp.com',
    storageBucket: 'eyyubiyepersonel.firebasestorage.app',
  );
}
